# Generated by Django 2.2.1 on 2019-05-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miyu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionwavfile',
            name='uploaded_file',
            field=models.FileField(upload_to=''),
        ),
    ]
